mod TEST-BASE is
  pr TEST .
  pr PLEXILITE .
  pr PLEXILITE-PREDS .

  subsort Config Bool < SystemUnderTest .

  --- Test Adapters

  op testConfiguration    : Configuration    -> Cell .
  op testExpression       : Expression       -> Cell .
  op testAttributes       : AttributeSet     -> Cell .
  op testQualified        : Qualified        -> Cell .
  op testBool             : Bool             -> Cell .
  op testModelCheckResult : ModelCheckResult -> Cell .
  op testSystem           : GlobalConfig     -> Cell .
  op testOperation        : Operation        -> Cell .
  op testQualifiedId      : Qualified        -> Cell .

  op testExternalInputs   : ExternalInputs   -> Cell .
  op testEInputsList      : EInputsList      -> Cell .
  op testValue            : Value            -> Cell .
  op testNat              : Nat              -> Cell .
  op testVariable         : Variable         -> Cell .
  op testGenerator        : ExternalInputGenerator -> Cell .

  op aConfiguration : Configuration -> Cell .
  op anExpression   : Expression    -> Cell .
  op anAttribute    : AttributeSet  -> Cell .
  op aSystem        : GlobalConfig  -> Cell .
  op somePairs      : List{Pair}    -> Cell .


  --- Test Stubs

  op Stub{Config} : -> Config [ctor] .


  --- Identifiers for test cases

  op A : -> Identifier .
  op B : -> Identifier .
  op C : -> Identifier .
  op M : -> Identifier .

endm
