mod TEST--INTERFACE is

  pr TEST-BASE .

  op interface--tests : -> TestResults .

  eq interface--tests =
    begin tests

      assert "updateGenerator calls update on the generator" from
        (updateGenerator(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ generator : noEnvGen ]
          , noExternalInputs
        )
        )
      reaches
          ([ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ generator : update(
                          noEnvGen,
                          [ environment : mtenvironment ]
                          [ interface : none ]
                          [ memory : none ]
                          [ generator : noEnvGen ],
                          noExternalInputs
                        ) ])
      end

    end tests
    .

endm