mod TEST--MODEL-CHECKING is

pr TEST-BASE .

op model-checking--tests : -> TestResults .
eq model-checking--tests = tests--commandIsExecuting-property .

op tests--commandIsExecuting-property : -> TestResults .
eq tests--commandIsExecuting-property = begin tests

    assert "commandIsExecuting returns true if the command is executing" from
        testBool(
            ( stop |
                [ nodes : < 'N : command | status: executing > ]
                [ interface : < 'C . 'N : command-on-execution | none > ]
            ) |= commandIsExecuting('C)
        )
    reaches
        testBool(
            true
        )
    end

    assert "commandIsExecuting returns false if the command is not executing" from
        testBool(
            ( stop |
                [ interface : < 'D : command-on-execution | none > ]
            ) |= commandIsExecuting('C)
        )
    reaches
        testBool(
            false
        )
    end


end tests .

endm