in ../../lib/test/test.maude
in ../../src/plexilite.maude
in ./base.maude
in ./atomic/test.maude
in ./reductions/test.maude
in ./expressions/test.maude
in ./model-checking.maude
in ./compiler/test.maude
in ./interface.maude

mod TEST-SUITE is

  pr TEST--ATOMIC .
  pr TEST--REDUCTIONS .
  pr TEST--EXPRESSIONS .
  pr TEST--MODEL-CHECKING .
  pr TEST--COMPILER .
  pr TEST--INTERFACE .

  eq tests =
    AllTestsPassed
    + atomic--tests
    + reductions--tests
    + expressions--tests
    + model-checking--tests
    + compiler--tests
    + interface--tests
    +
begin tests

    assert "An Update node" from
      testConfiguration(
        < 'anUpdate : update |
          pairs: (pair('val,const(val("foo"))) pair('taskId,var('waypointId))),
          ack: false >
      )
    reaches
      testConfiguration(
        < 'anUpdate : update |
          pairs: (pair('val,const(val("foo"))) pair('taskId,var('waypointId))),
          ack: false >
      )
    end

    assert "Compile Update node 1" from
      testConfiguration(
        compileNodes(update('anId, nilocdecl, none, pair('taskId,var('waypointId))), 'aRootId)
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : update |
          defaultInternalAttributes,
          pairs:   pair('taskId,var('waypointId)),
          startc:  const(val(true)),
          skip:    const(val(false)),
          pre:     const(val(true)),
          inv:     const(val(true)),
          exitc:   const(val(false)),
          repeatc: const(val(false)),
          post:    const(val(true)),
          endc:    hasRcvAck?('anId . 'aRootId),
          ack: false
        >
      )
    end

    assert "Compile Update node 2" from
      testConfiguration(
        compileNodes(update('anId, nilocdecl, endc: const(val(false)), pair('taskId,var('waypointId))), 'aRootId)
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : update |
          defaultInternalAttributes,
          pairs:   pair('taskId,var('waypointId)),
          startc:  const(val(true)),
          skip:    const(val(false)),
          pre:     const(val(true)),
          inv:     const(val(true)),
          exitc:   const(val(false)),
          repeatc: const(val(false)),
          post:    const(val(true)),
          endc:    const(val(false)) and hasRcvAck?('anId . 'aRootId),
          ack: false
        >
      )
    end

    assert "Compile Update node with multiple pairs" from
      testConfiguration(
        compileNodes(update('anId, nilocdecl, endc: const(val(false)), pair('taskId,var('waypointId)) pair('taskId2,var('waypointId2))), 'aRootId)
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : update |
          defaultInternalAttributes,
          pairs:   pair('taskId,var('waypointId)) pair('taskId2,var('waypointId2)),
          startc:  const(val(true)),
          skip:    const(val(false)),
          pre:     const(val(true)),
          inv:     const(val(true)),
          exitc:   const(val(false)),
          repeatc: const(val(false)),
          post:    const(val(true)),
          endc:    const(val(false)) and hasRcvAck?('anId . 'aRootId),
          ack: false
        >
      )
    end

    assert "Compile Command node 1" from
      testConfiguration(
        compileNodes(command('anId, nilocdecl, endc: const(val(false)), 'boolArrayCommand / nilpar / 'myBooleanArray), 'aRootId)
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : command |
          defaultInternalAttributes,
          command: 'boolArrayCommand / nilpar / 'myBooleanArray,
          commandInfo: nilarg / 'anId / idle,
          startc:  const(val(true)),
          skip:    const(val(false)),
          pre:     const(val(true)),
          inv:     const(val(true)),
          exitc:   const(val(false)),
          repeatc: const(val(false)),
          post:    const(val(true)),
          endc:    const(val(false)) or (cmdHandleIs?('anId . 'aRootId, CommandDenied) or cmdHandleIs?('anId . 'aRootId, CommandFailed))
        >
      )
    end

    assert "Compile Command node 2" from
      testConfiguration(
        compileNodes(command('anId, nilocdecl, endc: const(val(true)), 'boolArrayCommand / nilpar / 'myBooleanArray), 'aRootId)
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : command |
          defaultInternalAttributes,
          command: 'boolArrayCommand / nilpar / 'myBooleanArray,
          commandInfo: nilarg / 'anId / idle,
          startc:  const(val(true)),
          skip:    const(val(false)),
          pre:     const(val(true)),
          inv:     const(val(true)),
          exitc:   const(val(false)),
          repeatc: const(val(false)),
          post:    const(val(true)),
          endc:    const(val(true)) or (cmdHandleIs?('anId . 'aRootId, CommandDenied) or cmdHandleIs?('anId . 'aRootId, CommandFailed))
        >
      )
    end

    assert "Update interface with a CommandAbort 1" from
      testConfiguration(
        updateCommandInputs(
          < 'anId . 'aRootId : command-on-execution | arguments: nilarg, aborted: false >,
          (commandAbort('anId, nilarg, val(true)))
        )
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : command-on-execution | arguments: nilarg, aborted: true >
      )
    end

    assert "Update interface with empty external inputs" from
      testConfiguration(
        updateCommandInputs(
          < 'anId . 'aRootId : command-on-execution | arguments: nilarg, aborted: false >,
          noExternalInputs
        )
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : command-on-execution | arguments: nilarg, aborted: false >
      )
    end

    assert "Update interface with a CommandAck 1" from
      testConfiguration(
        updateCommandInputs(
          < 'anId . 'aRootId : command-on-execution | arguments: nilarg, handle: nothing >,
          (commandAck('anId, nilarg, CommandDenied))
        )
      )
    reaches
      testConfiguration(
        < 'anId . 'aRootId : command-on-execution | arguments: nilarg, handle: just(CommandDenied) >
      )
    end

    assert "Get command inputs 1" from
      testExternalInputs(
        getCommandInputs(
          commandAck('anId, nilarg, CommandDenied)
        )
      )
    reaches
      testExternalInputs(
        commandAck('anId, nilarg, CommandDenied)
      )
    end

    assert "Get command inputs 2" from
      testExternalInputs(
        getCommandInputs(
          commandAbort('anId, nilarg, val(true))
        )
      )
    reaches
      testExternalInputs(
        commandAbort('anId, nilarg, val(true))
      )
    end

    assert "Get command inputs 3" from
      testExternalInputs(
        getCommandInputs(
          commandAbort('anId, nilarg, val(true)) commandAck('anId, nilarg, CommandDenied)
        )
      )
    reaches
      testExternalInputs(
        commandAbort('anId, nilarg, val(true)) commandAck('anId, nilarg, CommandDenied)
      )
    end

    assert "Command abort completed 1" from
      testBool(
        hasAborted(
          < 'anId : command-on-execution | aborted: true >,
          < 'anId : command | active: true >,
          'anId
        )
      )
    reaches
      testBool(
        true
      )
    end

    assert "Command abort completed 2" from
      testBool(
        hasAborted(
          < 'anId : command-on-execution | aborted: false >,
          < 'anId : command | active: true >,
          'anId
        )
      )
    reaches
      testBool(
        false
      )
    end

    assert "Create len 0 empty IntArray" from
      testValue(
        createIntArray(0, mtIntArray)
      )
    reaches
      testValue(
        array(mtIntArray)
      )
    end

    assert "Create len 0 IntArray" from
      testValue(
        createIntArray(0, val(1) # val(2) # val(3))
      )
    reaches
      testValue(
        array(mtIntArray)
      )
    end

    assert "Create len 3 empty IntArray" from
      testValue(
        createIntArray(3, mtIntArray)
      )
    reaches
      testValue(
        array(unknownInt # unknownInt # unknownInt)
      )
    end

    assert "Create len 3 IntArray" from
      testValue(
        createIntArray(3, val(1) # val(2) # val(3))
      )
    reaches
      testValue(
        array(val(1) # val(2) # val(3))
      )
    end

    assert "Create len 3 IntArray with 2 values" from
      testValue(
        createIntArray(3, val(1) # val(2))
      )
    reaches
      testValue(
        array(val(1) # val(2) # unknownInt)
      )
    end

    assert "Create len 3 IntArray with 4 values" from
      testValue(
        createIntArray(3, val(1) # val(2) # val(3) # val(4))
      )
    reaches
      testValue(
        array(val(1) # val(2) # val(3))
      )
    end

    assert "length of empty IntArray" from
      testNat(
        length(mtIntArray)
      )
    reaches
      testNat(
        0
      )
    end

    assert "length of IntArray" from
      testNat(
        length(val(1) # val(2) # val(3))
      )
    reaches
      testNat(
        3
      )
    end

    assert "length of half initialised IntArray" from
      testNat(
        length(val(1) # val(2) # val(3) # unknownInt # unknownInt)
      )
    reaches
      testNat(
        5
      )
    end


end tests
.

endm

set show stats   off .
set show command off .
set show timing  off .

load ../../lib/test/test-runner.maude

reduce in TEST-RUNNER : runTests .
