mod TEST--ATOMIC--FAILING--UPDATE-NODE is

  pr TEST-BASE .

  op tests--atomic--failing--update-node : -> TestResults .

  eq tests--atomic--failing--update-node = begin tests

    assert "Failing update node with incomplete update" from
    failing(
        [ nodes :
            < A     : update | status: failing,
                               active: true,
                               outcome: failure(exited),
                               ack: false > ]
        [ microacts : mtactions ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    reaches
      failing(
        [ nodes :
            < A     : update | status: failing,
                               active: false,
                               outcome: failure(exited),
                               ack: false > ]
        [ microacts : mtactions ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    end

    assert "Failing update node follows path 1 (failing--update--01)" from
    failing(
        [ nodes :
            < A     : update | status: failing,
                               active: true,
                               outcome: failure(parentExited),
                               ack: true >]
        [ microacts : mtactions ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    reaches
      failing(
        [ nodes :
            < A     : update | status: failing,
                               active: false,
                               outcome: failure(parentExited),
                               ack: true > ]
        [ microacts : setStatus(A,finished),
                      logTransition(A, failing, finished, 1) ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    end

    assert "Failing update node follows path 2 (failing--update--02)" from
    failing(
        [ nodes :
            < A     : update | status: failing,
                               active: true,
                               outcome: failure(parentFailed),
                               ack: true >]
        [ microacts : mtactions ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    reaches
      failing(
        [ nodes :
            < A     : update | status: failing,
                               active: false,
                               outcome: failure(parentFailed),
                               ack: true > ]
        [ microacts : setStatus(A,finished),
                      logTransition(A, failing, finished, 2) ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    end

  assert "Failing update node follows path 3 (failing--update--03)" from
  failing(
        [ nodes :
            < A     : update | status: failing,
                               active: true,
                               outcome: failure(invariantFailed),
                               ack: true >]
        [ microacts : mtactions ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    reaches
      failing(
        [ nodes :
            < A     : update | status: failing,
                               active: false,
                               outcome: failure(invariantFailed),
                               ack: true > ]
        [ microacts : setStatus(A,iterationEnded),
                      logTransition(A, failing, iterationEnded, 3) ]
        [ environment : mtenvironment ] [ memory : none ]
      )
    end

  end tests .

endm