fmod GENERATORS--EMPTY-GENERATOR is
  pr GENERATORS--BASE-GENERATOR .

  vars Conf : Config .

  op emptyEnvGen : Nat -> ExternalInputGenerator .
  eq generate(emptyEnvGen(s N:Nat),Conf) = noExternalInputs .
  eq generate(emptyEnvGen(0),Conf) = nilEInputsList .

  eq update(emptyEnvGen(s N:Nat),Conf,EI:ExternalInputs) = emptyEnvGen(N:Nat) .

  eq isConsumed?(emptyEnvGen(s N:Nat),Conf) = false .
  eq isConsumed?(emptyEnvGen(0),Conf) = true [owise] .
endfm
