fmod FILTER-GENERATOR is

  protecting SYSTEM .
  protecting EVAL .

  op filter : InputGenerator Expression -> InputGenerator [ctor] .
  eq generate(filter(Gen,Expr),Cfg)
    =
    if bEval(Expr,Cfg)
      then generate(Gen,Cfg)
      else noInputs
    fi
  .
  eq update(filter(Gen,Expr),Cfg,In) = filter(update(Gen,Cfg,In),Expr) .
  eq cardinality(filter(Gen,Expr)) = cardinality(Gen) .

  vars Cfg : Config .
  vars Expr : Expression .
  vars Gen  : InputGenerator .
  vars In : Inputs .
endfm