load command.maude
load update.maude

mod TEST--INTERFACE is
  pr TEST-BASE .
  pr TEST--INTERFACE--COMMAND .
  pr TEST--INTERFACE--UPDATE  .

  op interface--tests : -> TestResults .

  eq interface--tests = test--interface--command + test--interface--update +
    begin tests

      assert "updateGenerator calls update on the generator" from
        (updateGenerator(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ generator : noEnvGen ]
          , noInputs
        )
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ generator : update(
                          noEnvGen,
                          [ environment : mtenvironment ]
                          [ interface : none ]
                          [ memory : none ]
                          [ generator : noEnvGen ],
                          noInputs
                        ) ]
      end

      assert "updateInterface calls updateUpdateAcks" from
        updateInterface(
          [ environment : mtenvironment ]
          [ interface : < A . B : update-on-execution | ack: false, pairs: < 'field ; const(val(0)) > > ]
          [ memory : none ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface :
            updateUpdateAcks(
              < A . B : update-on-execution | ack: false, pairs: < 'field ; const(val(0)) > >
              ,
              updateAck(A,true)
            ) ]
          [ memory : none ]
      end

      assert "updateInterfaceHistoryWithTracking tracks interface-history" from
        updateInterfaceHistoryWithTracking(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(B,true) ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) # updateAck(B,true) ]
      end

      assert "updateInterfaceHistoryWithTracking tracks interface-history" from
        updateInterfaceHistoryWithTracking(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(B,true) ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) # updateAck(B,true) ]
      end

      assert "updateInterfaceHistoryWithTracking prepends external inputs to list 0" from
        updateInterfaceHistoryWithTracking(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : noInputs ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) # noInputs ]
      end

      assert "updateInterfaceHistoryWithTracking prepends external inputs to list 1" from
        updateInterfaceHistoryWithTracking(
          [ environment : mtenvironment ]
          [ interface :
            < A . B : command-on-execution | arguments: nilarg, handle: nothing, order: 1, abort: CommandAbortIdle > ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) ]
          ,
          commandAck(A, nilarg, CommandAccepted)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface :
            < A . B : command-on-execution | arguments: nilarg, handle: just(CommandAccepted), order: 1, abort: CommandAbortIdle > ]
          [ memory : none ]
          [ interface-history : commandAck(A, nilarg, CommandAccepted) # updateAck(A,true) ]
      end

      assert "setInterfaceHistory tracks interface-history" from
        setInterfaceHistory(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(B,true) ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) ]
      end

      assert "setInterfaceHistory tracks interface-history" from
        setInterfaceHistory(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) ]
      end

      assert "updateInterfaceHistoryWithoutTracking prepends external inputs to list 0" from
        updateInterfaceHistoryWithoutTracking(
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : noInputs ]
          ,
          updateAck(A,true)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface : none ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) ]
      end

      assert "updateInterfaceHistoryWithoutTracking prepends external inputs to list 1" from
        updateInterfaceHistoryWithoutTracking(
          [ environment : mtenvironment ]
          [ interface :
            < A . B : command-on-execution | arguments: nilarg, handle: nothing, order: 1, abort: CommandAbortIdle > ]
          [ memory : none ]
          [ interface-history : updateAck(A,true) ]
          ,
          commandAck(A, nilarg, CommandAccepted)
        )
      reaches
          [ environment : mtenvironment ]
          [ interface :
            < A . B : command-on-execution | arguments: nilarg, handle: just(CommandAccepted), order: 1, abort: CommandAbortIdle > ]
          [ memory : none ]
          [ interface-history : commandAck(A, nilarg, CommandAccepted) ]
      end

    end tests
    .

endm