//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}DeclaredVariable"/>
 *         &lt;choice>
 *           &lt;element ref="{}BooleanRHS"/>
 *           &lt;element ref="{}NumericRHS"/>
 *           &lt;element ref="{}StringRHS"/>
 *           &lt;element ref="{}LookupRHS"/>
 *           &lt;element ref="{}ArrayRHS"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "integerVariable",
    "realVariable",
    "booleanVariable",
    "stringVariable",
    "arrayVariable",
    "arrayElement",
    "booleanRHS",
    "numericRHS",
    "stringRHS",
    "lookupRHS",
    "arrayRHS"
})
@XmlRootElement(name = "Assignment")
public class Assignment {

    @XmlElement(name = "IntegerVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String integerVariable;
    @XmlElement(name = "RealVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String realVariable;
    @XmlElement(name = "BooleanVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String booleanVariable;
    @XmlElement(name = "StringVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String stringVariable;
    @XmlElement(name = "ArrayVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String arrayVariable;
    @XmlElement(name = "ArrayElement")
    protected ArrayElement arrayElement;
    @XmlElement(name = "BooleanRHS")
    protected BooleanRHS booleanRHS;
    @XmlElement(name = "NumericRHS")
    protected NumericRHS numericRHS;
    @XmlElement(name = "StringRHS")
    protected StringRHS stringRHS;
    @XmlElement(name = "LookupRHS")
    protected LookupRHS lookupRHS;
    @XmlElement(name = "ArrayRHS")
    protected ArrayRHS arrayRHS;

    /**
     * Gets the value of the integerVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegerVariable() {
        return integerVariable;
    }

    /**
     * Sets the value of the integerVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegerVariable(String value) {
        this.integerVariable = value;
    }

    /**
     * Gets the value of the realVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealVariable() {
        return realVariable;
    }

    /**
     * Sets the value of the realVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealVariable(String value) {
        this.realVariable = value;
    }

    /**
     * Gets the value of the booleanVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBooleanVariable() {
        return booleanVariable;
    }

    /**
     * Sets the value of the booleanVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBooleanVariable(String value) {
        this.booleanVariable = value;
    }

    /**
     * Gets the value of the stringVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringVariable() {
        return stringVariable;
    }

    /**
     * Sets the value of the stringVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringVariable(String value) {
        this.stringVariable = value;
    }

    /**
     * Gets the value of the arrayVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrayVariable() {
        return arrayVariable;
    }

    /**
     * Sets the value of the arrayVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrayVariable(String value) {
        this.arrayVariable = value;
    }

    /**
     * Gets the value of the arrayElement property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayElement }
     *     
     */
    public ArrayElement getArrayElement() {
        return arrayElement;
    }

    /**
     * Sets the value of the arrayElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayElement }
     *     
     */
    public void setArrayElement(ArrayElement value) {
        this.arrayElement = value;
    }

    /**
     * Gets the value of the booleanRHS property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanRHS }
     *     
     */
    public BooleanRHS getBooleanRHS() {
        return booleanRHS;
    }

    /**
     * Sets the value of the booleanRHS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanRHS }
     *     
     */
    public void setBooleanRHS(BooleanRHS value) {
        this.booleanRHS = value;
    }

    /**
     * Gets the value of the numericRHS property.
     * 
     * @return
     *     possible object is
     *     {@link NumericRHS }
     *     
     */
    public NumericRHS getNumericRHS() {
        return numericRHS;
    }

    /**
     * Sets the value of the numericRHS property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericRHS }
     *     
     */
    public void setNumericRHS(NumericRHS value) {
        this.numericRHS = value;
    }

    /**
     * Gets the value of the stringRHS property.
     * 
     * @return
     *     possible object is
     *     {@link StringRHS }
     *     
     */
    public StringRHS getStringRHS() {
        return stringRHS;
    }

    /**
     * Sets the value of the stringRHS property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringRHS }
     *     
     */
    public void setStringRHS(StringRHS value) {
        this.stringRHS = value;
    }

    /**
     * Gets the value of the lookupRHS property.
     * 
     * @return
     *     possible object is
     *     {@link LookupRHS }
     *     
     */
    public LookupRHS getLookupRHS() {
        return lookupRHS;
    }

    /**
     * Sets the value of the lookupRHS property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupRHS }
     *     
     */
    public void setLookupRHS(LookupRHS value) {
        this.lookupRHS = value;
    }

    /**
     * Gets the value of the arrayRHS property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayRHS }
     *     
     */
    public ArrayRHS getArrayRHS() {
        return arrayRHS;
    }

    /**
     * Sets the value of the arrayRHS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayRHS }
     *     
     */
    public void setArrayRHS(ArrayRHS value) {
        this.arrayRHS = value;
    }

}
