//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="Type" type="{}TypeValues"/>
 *         &lt;element name="MaxSize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="InitialValue" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{}IntegerValue" maxOccurs="unbounded"/>
 *                   &lt;element ref="{}RealValue" maxOccurs="unbounded"/>
 *                   &lt;element ref="{}BooleanValue" maxOccurs="unbounded"/>
 *                   &lt;element ref="{}StringValue" maxOccurs="unbounded"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "type",
    "maxSize",
    "initialValue"
})
@XmlRootElement(name = "DeclareArray")
public class DeclareArray {

    @XmlElement(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlElement(name = "Type", required = true)
    protected TypeValues type;
    @XmlElement(name = "MaxSize", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxSize;
    @XmlElement(name = "InitialValue")
    protected DeclareArray.InitialValue initialValue;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeValues }
     *     
     */
    public TypeValues getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeValues }
     *     
     */
    public void setType(TypeValues value) {
        this.type = value;
    }

    /**
     * Gets the value of the maxSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxSize() {
        return maxSize;
    }

    /**
     * Sets the value of the maxSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxSize(BigInteger value) {
        this.maxSize = value;
    }

    /**
     * Gets the value of the initialValue property.
     * 
     * @return
     *     possible object is
     *     {@link DeclareArray.InitialValue }
     *     
     */
    public DeclareArray.InitialValue getInitialValue() {
        return initialValue;
    }

    /**
     * Sets the value of the initialValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclareArray.InitialValue }
     *     
     */
    public void setInitialValue(DeclareArray.InitialValue value) {
        this.initialValue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{}IntegerValue" maxOccurs="unbounded"/>
     *         &lt;element ref="{}RealValue" maxOccurs="unbounded"/>
     *         &lt;element ref="{}BooleanValue" maxOccurs="unbounded"/>
     *         &lt;element ref="{}StringValue" maxOccurs="unbounded"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "integerValue",
        "realValue",
        "booleanValue",
        "stringValue"
    })
    public static class InitialValue {

        @XmlElement(name = "IntegerValue")
        protected List<BigInteger> integerValue;
        @XmlElement(name = "RealValue", type = Double.class)
        protected List<Double> realValue;
        @XmlElement(name = "BooleanValue", type = Boolean.class)
        protected List<Boolean> booleanValue;
        @XmlElement(name = "StringValue")
        protected List<String> stringValue;

        /**
         * Gets the value of the integerValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the integerValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIntegerValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getIntegerValue() {
            if (integerValue == null) {
                integerValue = new ArrayList<BigInteger>();
            }
            return this.integerValue;
        }

        /**
         * Gets the value of the realValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the realValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRealValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Double }
         * 
         * 
         */
        public List<Double> getRealValue() {
            if (realValue == null) {
                realValue = new ArrayList<Double>();
            }
            return this.realValue;
        }

        /**
         * Gets the value of the booleanValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the booleanValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBooleanValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Boolean }
         * 
         * 
         */
        public List<Boolean> getBooleanValue() {
            if (booleanValue == null) {
                booleanValue = new ArrayList<Boolean>();
            }
            return this.booleanValue;
        }

        /**
         * Gets the value of the stringValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stringValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStringValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getStringValue() {
            if (stringValue == null) {
                stringValue = new ArrayList<String>();
            }
            return this.stringValue;
        }

    }

}
