//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.nianet.plexil.plexilxml2maude.jaxbmodel.ext.BooleanExpression;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}StringExpression" maxOccurs="2" minOccurs="2"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stringExpression"
})
@XmlRootElement(name = "EQString")
public class EQString implements BooleanExpression{

    @Override
	public String getExpression(Map<String,String> variablesContext) {
		// TODO Auto-generated method stub
		throw new RuntimeException("EQ-String - getExpression:not implemented yet.");
	}

	@XmlElementRefs({
        @XmlElementRef(name = "LookupOnChange", type = LookupOnChange.class),
        @XmlElementRef(name = "StringValue", type = JAXBElement.class),
        @XmlElementRef(name = "Concat", type = Concat.class),
        @XmlElementRef(name = "LookupNow", type = LookupNow.class),
        @XmlElementRef(name = "StringVariable", type = JAXBElement.class),
        @XmlElementRef(name = "ArrayElement", type = ArrayElement.class)
    })
    protected List<Object> stringExpression;

    /**
     * Gets the value of the stringExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LookupNow }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link LookupOnChange }
     * {@link ArrayElement }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Concat }
     * 
     * 
     */
    public List<Object> getStringExpression() {
        if (stringExpression == null) {
            stringExpression = new ArrayList<Object>();
        }
        return this.stringExpression;
    }

}
