//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.nianet.plexil.plexilxml2maude.jaxbmodel.ext.BooleanExpression;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{}DeclaredVariable"/>
 *         &lt;group ref="{}Lookup"/>
 *         &lt;element ref="{}NodeStateVariable"/>
 *         &lt;element ref="{}NodeOutcomeVariable"/>
 *         &lt;element ref="{}NodeTimepointValue"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "integerVariable",
    "realVariable",
    "booleanVariable",
    "stringVariable",
    "arrayVariable",
    "arrayElement",
    "lookupOnChange",
    "lookupNow",
    "nodeStateVariable",
    "nodeOutcomeVariable",
    "nodeTimepointValue"
})
@XmlRootElement(name = "IsKnown")
public class IsKnown implements BooleanExpression {

    @Override
	public String getExpression(Map<String,String> variablesContext) {
		// TODO Auto-generated method stub
		throw new RuntimeException("IsKnown - getExpression:not implemented yet.");
	}

	@XmlElement(name = "IntegerVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String integerVariable;
    @XmlElement(name = "RealVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String realVariable;
    @XmlElement(name = "BooleanVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String booleanVariable;
    @XmlElement(name = "StringVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String stringVariable;
    @XmlElement(name = "ArrayVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String arrayVariable;
    @XmlElement(name = "ArrayElement")
    protected ArrayElement arrayElement;
    @XmlElement(name = "LookupOnChange")
    protected LookupOnChange lookupOnChange;
    @XmlElement(name = "LookupNow")
    protected LookupNow lookupNow;
    @XmlElement(name = "NodeStateVariable")
    protected NodeStateVariable nodeStateVariable;
    @XmlElement(name = "NodeOutcomeVariable")
    protected NodeOutcomeVariable nodeOutcomeVariable;
    @XmlElement(name = "NodeTimepointValue")
    protected NodeTimepointValue nodeTimepointValue;

    /**
     * Gets the value of the integerVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegerVariable() {
        return integerVariable;
    }

    /**
     * Sets the value of the integerVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegerVariable(String value) {
        this.integerVariable = value;
    }

    /**
     * Gets the value of the realVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealVariable() {
        return realVariable;
    }

    /**
     * Sets the value of the realVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealVariable(String value) {
        this.realVariable = value;
    }

    /**
     * Gets the value of the booleanVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBooleanVariable() {
        return booleanVariable;
    }

    /**
     * Sets the value of the booleanVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBooleanVariable(String value) {
        this.booleanVariable = value;
    }

    /**
     * Gets the value of the stringVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringVariable() {
        return stringVariable;
    }

    /**
     * Sets the value of the stringVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringVariable(String value) {
        this.stringVariable = value;
    }

    /**
     * Gets the value of the arrayVariable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrayVariable() {
        return arrayVariable;
    }

    /**
     * Sets the value of the arrayVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrayVariable(String value) {
        this.arrayVariable = value;
    }

    /**
     * Gets the value of the arrayElement property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayElement }
     *     
     */
    public ArrayElement getArrayElement() {
        return arrayElement;
    }

    /**
     * Sets the value of the arrayElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayElement }
     *     
     */
    public void setArrayElement(ArrayElement value) {
        this.arrayElement = value;
    }

    /**
     * Gets the value of the lookupOnChange property.
     * 
     * @return
     *     possible object is
     *     {@link LookupOnChange }
     *     
     */
    public LookupOnChange getLookupOnChange() {
        return lookupOnChange;
    }

    /**
     * Sets the value of the lookupOnChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupOnChange }
     *     
     */
    public void setLookupOnChange(LookupOnChange value) {
        this.lookupOnChange = value;
    }

    /**
     * Gets the value of the lookupNow property.
     * 
     * @return
     *     possible object is
     *     {@link LookupNow }
     *     
     */
    public LookupNow getLookupNow() {
        return lookupNow;
    }

    /**
     * Sets the value of the lookupNow property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupNow }
     *     
     */
    public void setLookupNow(LookupNow value) {
        this.lookupNow = value;
    }

    /**
     * Gets the value of the nodeStateVariable property.
     * 
     * @return
     *     possible object is
     *     {@link NodeStateVariable }
     *     
     */
    public NodeStateVariable getNodeStateVariable() {
        return nodeStateVariable;
    }

    /**
     * Sets the value of the nodeStateVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeStateVariable }
     *     
     */
    public void setNodeStateVariable(NodeStateVariable value) {
        this.nodeStateVariable = value;
    }

    /**
     * Gets the value of the nodeOutcomeVariable property.
     * 
     * @return
     *     possible object is
     *     {@link NodeOutcomeVariable }
     *     
     */
    public NodeOutcomeVariable getNodeOutcomeVariable() {
        return nodeOutcomeVariable;
    }

    /**
     * Sets the value of the nodeOutcomeVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeOutcomeVariable }
     *     
     */
    public void setNodeOutcomeVariable(NodeOutcomeVariable value) {
        this.nodeOutcomeVariable = value;
    }

    /**
     * Gets the value of the nodeTimepointValue property.
     * 
     * @return
     *     possible object is
     *     {@link NodeTimepointValue }
     *     
     */
    public NodeTimepointValue getNodeTimepointValue() {
        return nodeTimepointValue;
    }

    /**
     * Sets the value of the nodeTimepointValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeTimepointValue }
     *     
     */
    public void setNodeTimepointValue(NodeTimepointValue value) {
        this.nodeTimepointValue = value;
    }

}
