//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}Lookup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lookupOnChange",
    "lookupNow"
})
@XmlRootElement(name = "LookupRHS")
public class LookupRHS {

    @XmlElement(name = "LookupOnChange")
    protected LookupOnChange lookupOnChange;
    @XmlElement(name = "LookupNow")
    protected LookupNow lookupNow;

    /**
     * Gets the value of the lookupOnChange property.
     * 
     * @return
     *     possible object is
     *     {@link LookupOnChange }
     *     
     */
    public LookupOnChange getLookupOnChange() {
        return lookupOnChange;
    }

    /**
     * Sets the value of the lookupOnChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupOnChange }
     *     
     */
    public void setLookupOnChange(LookupOnChange value) {
        this.lookupOnChange = value;
    }

    /**
     * Gets the value of the lookupNow property.
     * 
     * @return
     *     possible object is
     *     {@link LookupNow }
     *     
     */
    public LookupNow getLookupNow() {
        return lookupNow;
    }

    /**
     * Sets the value of the lookupNow property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupNow }
     *     
     */
    public void setLookupNow(LookupNow value) {
        this.lookupNow = value;
    }

}
