//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import java.util.Map;
import java.util.StringTokenizer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.nianet.plexil.plexilxml2maude.jaxbmodel.ext.BooleanExpression;
import org.nianet.plexil.plexilxml2maude.jaxbmodel.ext.NodeVariable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}Name"/>
 *           &lt;element name="StateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Tolerance" minOccurs="0"/>
 *         &lt;element ref="{}Arguments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "stateName",
    "tolerance",
    "arguments"
})
@XmlRootElement(name = "LookupOnChange")
public class LookupOnChange implements BooleanExpression{

    @Override
	public String getExpression(Map<String, String> variablesContext) {
    	if (this.getTolerance()!=null){
    		if (this.getTolerance().getRealValue()!=null){
    			Float thval=new Float(this.getTolerance().getRealValue());
    			
    			return "lookupOnChange ("+adjustLookupResourceName(this.getName().getStringValue())+",v("+Math.abs(thval.intValue())+"))";	
    		}
    		else if (this.getTolerance().getRealVariable()!=null){
    			throw new RuntimeException("LookupOnChange expressions with real variable as thresold are not supported.");
    			//String varName=new NodeVariable(this.getTolerance().getRealVariable()).getNoVarExpression(variablesContext);
    			//return "lookupOnChange ("+adjustLookupResourceName(this.getName().getStringValue())+","+varName+")";
    		}    		
    		else{
    			throw new RuntimeException("LookupOnChange expressions with integer variable as thresold are not supported.");
    		}
    	}
    	else{
    		return "lookupOnChange ("+adjustLookupResourceName(this.getName().getStringValue())+",v(0))";	
    	}
		//return "lookup ("+adjustLookupResourceName(this.getName().getStringValue())+")";
		
	}

	private static String adjustLookupResourceName(String cname){
		String adjustedCmd="";
		StringTokenizer st=new StringTokenizer(cname,".");
		while (st.hasMoreTokens()){
			String tok=st.nextToken().trim();
			adjustedCmd+="'"+tok+(st.hasMoreTokens()?" . ":"");			
		}
				
		return adjustedCmd;
	}

    
	@XmlElement(name = "Name")
    protected Name name;
    @XmlElement(name = "StateName")
    protected String stateName;
    @XmlElement(name = "Tolerance")
    protected Tolerance tolerance;
    @XmlElement(name = "Arguments")
    protected Arguments arguments;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the stateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateName() {
        return stateName;
    }

    /**
     * Sets the value of the stateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateName(String value) {
        this.stateName = value;
    }

    /**
     * Gets the value of the tolerance property.
     * 
     * @return
     *     possible object is
     *     {@link Tolerance }
     *     
     */
    public Tolerance getTolerance() {
        return tolerance;
    }

    /**
     * Sets the value of the tolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tolerance }
     *     
     */
    public void setTolerance(Tolerance value) {
        this.tolerance = value;
    }

    /**
     * Gets the value of the arguments property.
     * 
     * @return
     *     possible object is
     *     {@link Arguments }
     *     
     */
    public Arguments getArguments() {
        return arguments;
    }

    /**
     * Sets the value of the arguments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arguments }
     *     
     */
    public void setArguments(Arguments value) {
        this.arguments = value;
    }


    
}
