//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}NodeRef"/>
 *           &lt;element ref="{}NodeId"/>
 *         &lt;/choice>
 *         &lt;element ref="{}NodeStateValue"/>
 *         &lt;element ref="{}Timepoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nodeRef",
    "nodeId",
    "nodeStateValue",
    "timepoint"
})
@XmlRootElement(name = "NodeTimepointValue")
public class NodeTimepointValue {

    @XmlElement(name = "NodeRef")
    protected NodeRef nodeRef;
    @XmlElement(name = "NodeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String nodeId;
    @XmlElement(name = "NodeStateValue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nodeStateValue;
    @XmlElement(name = "Timepoint", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String timepoint;

    /**
     * Gets the value of the nodeRef property.
     * 
     * @return
     *     possible object is
     *     {@link NodeRef }
     *     
     */
    public NodeRef getNodeRef() {
        return nodeRef;
    }

    /**
     * Sets the value of the nodeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeRef }
     *     
     */
    public void setNodeRef(NodeRef value) {
        this.nodeRef = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the nodeStateValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeStateValue() {
        return nodeStateValue;
    }

    /**
     * Sets the value of the nodeStateValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeStateValue(String value) {
        this.nodeStateValue = value;
    }

    /**
     * Gets the value of the timepoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimepoint() {
        return timepoint;
    }

    /**
     * Sets the value of the timepoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimepoint(String value) {
        this.timepoint = value;
    }

}
