//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IntegerValue_QNAME = new QName("", "IntegerValue");
    private final static QName _RealValue_QNAME = new QName("", "RealValue");
    private final static QName _NodeOutcomeValue_QNAME = new QName("", "NodeOutcomeValue");
    private final static QName _RealVariable_QNAME = new QName("", "RealVariable");
    private final static QName _NodeStateValue_QNAME = new QName("", "NodeStateValue");
    private final static QName _StringValue_QNAME = new QName("", "StringValue");
    private final static QName _BooleanVariable_QNAME = new QName("", "BooleanVariable");
    private final static QName _IntegerVariable_QNAME = new QName("", "IntegerVariable");
    private final static QName _NodeId_QNAME = new QName("", "NodeId");
    private final static QName _Timepoint_QNAME = new QName("", "Timepoint");
    private final static QName _BooleanValue_QNAME = new QName("", "BooleanValue");
    private final static QName _StringVariable_QNAME = new QName("", "StringVariable");
    private final static QName _Return_QNAME = new QName("", "Return");
    private final static QName _NodeCommandHandleValue_QNAME = new QName("", "NodeCommandHandleValue");
    private final static QName _NodeFailureValue_QNAME = new QName("", "NodeFailureValue");
    private final static QName _SUBArrayMaxSize_QNAME = new QName("", "ArrayMaxSize");
    private final static QName _SUBArraySize_QNAME = new QName("", "ArraySize");
    private final static QName _ArgumentsArrayVariable_QNAME = new QName("", "ArrayVariable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NodeStateVariable }
     * 
     */
    public NodeStateVariable createNodeStateVariable() {
        return new NodeStateVariable();
    }

    /**
     * Create an instance of {@link VariableDeclarations }
     * 
     */
    public VariableDeclarations createVariableDeclarations() {
        return new VariableDeclarations();
    }

    /**
     * Create an instance of {@link NodeFailureVariable }
     * 
     */
    public NodeFailureVariable createNodeFailureVariable() {
        return new NodeFailureVariable();
    }

    /**
     * Create an instance of {@link LT }
     * 
     */
    public LT createLT() {
        return new LT();
    }

    /**
     * Create an instance of {@link Resource.ResourceReleaseAtTermination }
     * 
     */
    public Resource.ResourceReleaseAtTermination createResourceResourceReleaseAtTermination() {
        return new Resource.ResourceReleaseAtTermination();
    }

    /**
     * Create an instance of {@link StringRHS }
     * 
     */
    public StringRHS createStringRHS() {
        return new StringRHS();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Resource.ResourceUpperBound }
     * 
     */
    public Resource.ResourceUpperBound createResourceResourceUpperBound() {
        return new Resource.ResourceUpperBound();
    }

    /**
     * Create an instance of {@link NodeList }
     * 
     */
    public NodeList createNodeList() {
        return new NodeList();
    }

    /**
     * Create an instance of {@link RepeatCondition }
     * 
     */
    public RepeatCondition createRepeatCondition() {
        return new RepeatCondition();
    }

    /**
     * Create an instance of {@link GlobalDeclarations }
     * 
     */
    public GlobalDeclarations createGlobalDeclarations() {
        return new GlobalDeclarations();
    }

    /**
     * Create an instance of {@link Resource.ResourcePriority }
     * 
     */
    public Resource.ResourcePriority createResourceResourcePriority() {
        return new Resource.ResourcePriority();
    }

    /**
     * Create an instance of {@link DeclareVariable.InitialValue }
     * 
     */
    public DeclareVariable.InitialValue createDeclareVariableInitialValue() {
        return new DeclareVariable.InitialValue();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link LE }
     * 
     */
    public LE createLE() {
        return new LE();
    }

    /**
     * Create an instance of {@link EQInternal }
     * 
     */
    public EQInternal createEQInternal() {
        return new EQInternal();
    }

    /**
     * Create an instance of {@link In }
     * 
     */
    public In createIn() {
        return new In();
    }

    /**
     * Create an instance of {@link BooleanRHS }
     * 
     */
    public BooleanRHS createBooleanRHS() {
        return new BooleanRHS();
    }

    /**
     * Create an instance of {@link LookupRHS }
     * 
     */
    public LookupRHS createLookupRHS() {
        return new LookupRHS();
    }

    /**
     * Create an instance of {@link NodeOutcomeVariable }
     * 
     */
    public NodeOutcomeVariable createNodeOutcomeVariable() {
        return new NodeOutcomeVariable();
    }

    /**
     * Create an instance of {@link GE }
     * 
     */
    public GE createGE() {
        return new GE();
    }

    /**
     * Create an instance of {@link Interface }
     * 
     */
    public Interface createInterface() {
        return new Interface();
    }

    /**
     * Create an instance of {@link NodeCommandHandleVariable }
     * 
     */
    public NodeCommandHandleVariable createNodeCommandHandleVariable() {
        return new NodeCommandHandleVariable();
    }

    /**
     * Create an instance of {@link NumericRHS }
     * 
     */
    public NumericRHS createNumericRHS() {
        return new NumericRHS();
    }

    /**
     * Create an instance of {@link ArrayRHS }
     * 
     */
    public ArrayRHS createArrayRHS() {
        return new ArrayRHS();
    }

    /**
     * Create an instance of {@link OR }
     * 
     */
    public OR createOR() {
        return new OR();
    }

    /**
     * Create an instance of {@link LibraryNodeCall }
     * 
     */
    public LibraryNodeCall createLibraryNodeCall() {
        return new LibraryNodeCall();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link LibraryNodeDeclaration }
     * 
     */
    public LibraryNodeDeclaration createLibraryNodeDeclaration() {
        return new LibraryNodeDeclaration();
    }

    /**
     * Create an instance of {@link NodeRef }
     * 
     */
    public NodeRef createNodeRef() {
        return new NodeRef();
    }

    /**
     * Create an instance of {@link Arguments }
     * 
     */
    public Arguments createArguments() {
        return new Arguments();
    }

    /**
     * Create an instance of {@link MUL }
     * 
     */
    public MUL createMUL() {
        return new MUL();
    }

    /**
     * Create an instance of {@link CommandDeclaration }
     * 
     */
    public CommandDeclaration createCommandDeclaration() {
        return new CommandDeclaration();
    }

    /**
     * Create an instance of {@link DeclareArray.InitialValue }
     * 
     */
    public DeclareArray.InitialValue createDeclareArrayInitialValue() {
        return new DeclareArray.InitialValue();
    }

    /**
     * Create an instance of {@link SQRT }
     * 
     */
    public SQRT createSQRT() {
        return new SQRT();
    }

    /**
     * Create an instance of {@link NEInternal }
     * 
     */
    public NEInternal createNEInternal() {
        return new NEInternal();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link StartCondition }
     * 
     */
    public StartCondition createStartCondition() {
        return new StartCondition();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link AND }
     * 
     */
    public AND createAND() {
        return new AND();
    }

    /**
     * Create an instance of {@link SkipCondition }
     * 
     */
    public SkipCondition createSkipCondition() {
        return new SkipCondition();
    }

    /**
     * Create an instance of {@link NodeTimepointValue }
     * 
     */
    public NodeTimepointValue createNodeTimepointValue() {
        return new NodeTimepointValue();
    }

    /**
     * Create an instance of {@link Tolerance }
     * 
     */
    public Tolerance createTolerance() {
        return new Tolerance();
    }

    /**
     * Create an instance of {@link Concat }
     * 
     */
    public Concat createConcat() {
        return new Concat();
    }

    /**
     * Create an instance of {@link FunctionCall }
     * 
     */
    public FunctionCall createFunctionCall() {
        return new FunctionCall();
    }

    /**
     * Create an instance of {@link PreCondition }
     * 
     */
    public PreCondition createPreCondition() {
        return new PreCondition();
    }

    /**
     * Create an instance of {@link ADD }
     * 
     */
    public ADD createADD() {
        return new ADD();
    }

    /**
     * Create an instance of {@link Pair }
     * 
     */
    public Pair createPair() {
        return new Pair();
    }

    /**
     * Create an instance of {@link DeclareArray }
     * 
     */
    public DeclareArray createDeclareArray() {
        return new DeclareArray();
    }

    /**
     * Create an instance of {@link Alias }
     * 
     */
    public Alias createAlias() {
        return new Alias();
    }

    /**
     * Create an instance of {@link DeclareVariable }
     * 
     */
    public DeclareVariable createDeclareVariable() {
        return new DeclareVariable();
    }

    /**
     * Create an instance of {@link NodeBody }
     * 
     */
    public NodeBody createNodeBody() {
        return new NodeBody();
    }

    /**
     * Create an instance of {@link EndCondition }
     * 
     */
    public EndCondition createEndCondition() {
        return new EndCondition();
    }

    /**
     * Create an instance of {@link Resource.ResourceLowerBound }
     * 
     */
    public Resource.ResourceLowerBound createResourceResourceLowerBound() {
        return new Resource.ResourceLowerBound();
    }

    /**
     * Create an instance of {@link InOut }
     * 
     */
    public InOut createInOut() {
        return new InOut();
    }

    /**
     * Create an instance of {@link ResourceList }
     * 
     */
    public ResourceList createResourceList() {
        return new ResourceList();
    }

    /**
     * Create an instance of {@link LookupNow }
     * 
     */
    public LookupNow createLookupNow() {
        return new LookupNow();
    }

    /**
     * Create an instance of {@link ArrayElement.Index }
     * 
     */
    public ArrayElement.Index createArrayElementIndex() {
        return new ArrayElement.Index();
    }

    /**
     * Create an instance of {@link InvariantCondition }
     * 
     */
    public InvariantCondition createInvariantCondition() {
        return new InvariantCondition();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link NENumeric }
     * 
     */
    public NENumeric createNENumeric() {
        return new NENumeric();
    }

    /**
     * Create an instance of {@link ArrayElement }
     * 
     */
    public ArrayElement createArrayElement() {
        return new ArrayElement();
    }

    /**
     * Create an instance of {@link Resource.ResourceName }
     * 
     */
    public Resource.ResourceName createResourceResourceName() {
        return new Resource.ResourceName();
    }

    /**
     * Create an instance of {@link NOT }
     * 
     */
    public NOT createNOT() {
        return new NOT();
    }

    /**
     * Create an instance of {@link IsKnown }
     * 
     */
    public IsKnown createIsKnown() {
        return new IsKnown();
    }

    /**
     * Create an instance of {@link DIV }
     * 
     */
    public DIV createDIV() {
        return new DIV();
    }

    /**
     * Create an instance of {@link GT }
     * 
     */
    public GT createGT() {
        return new GT();
    }

    /**
     * Create an instance of {@link XOR }
     * 
     */
    public XOR createXOR() {
        return new XOR();
    }

    /**
     * Create an instance of {@link EQString }
     * 
     */
    public EQString createEQString() {
        return new EQString();
    }

    /**
     * Create an instance of {@link EQNumeric }
     * 
     */
    public EQNumeric createEQNumeric() {
        return new EQNumeric();
    }

    /**
     * Create an instance of {@link NEString }
     * 
     */
    public NEString createNEString() {
        return new NEString();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link SUB }
     * 
     */
    public SUB createSUB() {
        return new SUB();
    }

    /**
     * Create an instance of {@link LookupOnChange }
     * 
     */
    public LookupOnChange createLookupOnChange() {
        return new LookupOnChange();
    }

    /**
     * Create an instance of {@link StateDeclaration }
     * 
     */
    public StateDeclaration createStateDeclaration() {
        return new StateDeclaration();
    }

    /**
     * Create an instance of {@link PlexilPlan }
     * 
     */
    public PlexilPlan createPlexilPlan() {
        return new PlexilPlan();
    }

    /**
     * Create an instance of {@link Assignment }
     * 
     */
    public Assignment createAssignment() {
        return new Assignment();
    }

    /**
     * Create an instance of {@link EQBoolean }
     * 
     */
    public EQBoolean createEQBoolean() {
        return new EQBoolean();
    }

    /**
     * Create an instance of {@link ABS }
     * 
     */
    public ABS createABS() {
        return new ABS();
    }

    /**
     * Create an instance of {@link NEBoolean }
     * 
     */
    public NEBoolean createNEBoolean() {
        return new NEBoolean();
    }

    /**
     * Create an instance of {@link PostCondition }
     * 
     */
    public PostCondition createPostCondition() {
        return new PostCondition();
    }

    /**
     * Create an instance of {@link FunctionDeclaration }
     * 
     */
    public FunctionDeclaration createFunctionDeclaration() {
        return new FunctionDeclaration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IntegerValue")
    public JAXBElement<BigInteger> createIntegerValue(BigInteger value) {
        return new JAXBElement<BigInteger>(_IntegerValue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RealValue")
    public JAXBElement<Double> createRealValue(Double value) {
        return new JAXBElement<Double>(_RealValue_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NodeOutcomeValue")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNodeOutcomeValue(String value) {
        return new JAXBElement<String>(_NodeOutcomeValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RealVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRealVariable(String value) {
        return new JAXBElement<String>(_RealVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NodeStateValue")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNodeStateValue(String value) {
        return new JAXBElement<String>(_NodeStateValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StringValue")
    public JAXBElement<String> createStringValue(String value) {
        return new JAXBElement<String>(_StringValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BooleanVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBooleanVariable(String value) {
        return new JAXBElement<String>(_BooleanVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IntegerVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIntegerVariable(String value) {
        return new JAXBElement<String>(_IntegerVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NodeId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNodeId(String value) {
        return new JAXBElement<String>(_NodeId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Timepoint")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTimepoint(String value) {
        return new JAXBElement<String>(_Timepoint_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BooleanValue")
    public JAXBElement<Boolean> createBooleanValue(Boolean value) {
        return new JAXBElement<Boolean>(_BooleanValue_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StringVariable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStringVariable(String value) {
        return new JAXBElement<String>(_StringVariable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Return")
    public JAXBElement<Return> createReturn(Return value) {
        return new JAXBElement<Return>(_Return_QNAME, Return.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NodeCommandHandleValue")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNodeCommandHandleValue(String value) {
        return new JAXBElement<String>(_NodeCommandHandleValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NodeFailureValue")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNodeFailureValue(String value) {
        return new JAXBElement<String>(_NodeFailureValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = SUB.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSUBArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, SUB.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = SUB.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSUBArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, SUB.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = DIV.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDIVArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, DIV.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = DIV.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDIVArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, DIV.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = GT.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGTArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, GT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = GT.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGTArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, GT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = LT.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLTArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, LT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = LT.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLTArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, LT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = ADD.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createADDArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, ADD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = ADD.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createADDArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, ADD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = NENumeric.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNENumericArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, NENumeric.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = NENumeric.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNENumericArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, NENumeric.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = LE.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLEArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, LE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = LE.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLEArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, LE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = EQNumeric.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEQNumericArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, EQNumeric.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = EQNumeric.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEQNumericArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, EQNumeric.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayVariable", scope = Arguments.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createArgumentsArrayVariable(String value) {
        return new JAXBElement<String>(_ArgumentsArrayVariable_QNAME, String.class, Arguments.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = MUL.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMULArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, MUL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = MUL.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMULArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, MUL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrayMaxSize", scope = GE.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGEArrayMaxSize(String value) {
        return new JAXBElement<String>(_SUBArrayMaxSize_QNAME, String.class, GE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArraySize", scope = GE.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGEArraySize(String value) {
        return new JAXBElement<String>(_SUBArraySize_QNAME, String.class, GE.class, value);
    }

}
