//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 09:23:03 AM COT 
//


package org.nianet.plexil.plexilxml2maude.jaxbmodel;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ResourceName">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}StringExpression"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResourcePriority">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}NumericExpression"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResourceLowerBound" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}NumericExpression"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResourceUpperBound" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}NumericExpression"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ResourceReleaseAtTermination" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{}BooleanExpression"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Resource")
public class Resource {

    @XmlElement(name = "ResourceName", required = true)
    protected Resource.ResourceName resourceName;
    @XmlElement(name = "ResourcePriority", required = true)
    protected Resource.ResourcePriority resourcePriority;
    @XmlElement(name = "ResourceLowerBound")
    protected Resource.ResourceLowerBound resourceLowerBound;
    @XmlElement(name = "ResourceUpperBound")
    protected Resource.ResourceUpperBound resourceUpperBound;
    @XmlElement(name = "ResourceReleaseAtTermination")
    protected Resource.ResourceReleaseAtTermination resourceReleaseAtTermination;

        
    /**
     * Gets the value of the resourceName property.
     * 
     * @return
     *     possible object is
     *     {@link Resource.ResourceName }
     *     
     */
    public Resource.ResourceName getResourceName() {
        return resourceName;
    }

    /**
     * Sets the value of the resourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource.ResourceName }
     *     
     */
    public void setResourceName(Resource.ResourceName value) {
        this.resourceName = value;
    }

    /**
     * Gets the value of the resourcePriority property.
     * 
     * @return
     *     possible object is
     *     {@link Resource.ResourcePriority }
     *     
     */
    public Resource.ResourcePriority getResourcePriority() {
        return resourcePriority;
    }

    /**
     * Sets the value of the resourcePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource.ResourcePriority }
     *     
     */
    public void setResourcePriority(Resource.ResourcePriority value) {
        this.resourcePriority = value;
    }

    /**
     * Gets the value of the resourceLowerBound property.
     * 
     * @return
     *     possible object is
     *     {@link Resource.ResourceLowerBound }
     *     
     */
    public Resource.ResourceLowerBound getResourceLowerBound() {
        return resourceLowerBound;
    }

    /**
     * Sets the value of the resourceLowerBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource.ResourceLowerBound }
     *     
     */
    public void setResourceLowerBound(Resource.ResourceLowerBound value) {
        this.resourceLowerBound = value;
    }

    /**
     * Gets the value of the resourceUpperBound property.
     * 
     * @return
     *     possible object is
     *     {@link Resource.ResourceUpperBound }
     *     
     */
    public Resource.ResourceUpperBound getResourceUpperBound() {
        return resourceUpperBound;
    }

    /**
     * Sets the value of the resourceUpperBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource.ResourceUpperBound }
     *     
     */
    public void setResourceUpperBound(Resource.ResourceUpperBound value) {
        this.resourceUpperBound = value;
    }

    /**
     * Gets the value of the resourceReleaseAtTermination property.
     * 
     * @return
     *     possible object is
     *     {@link Resource.ResourceReleaseAtTermination }
     *     
     */
    public Resource.ResourceReleaseAtTermination getResourceReleaseAtTermination() {
        return resourceReleaseAtTermination;
    }

    /**
     * Sets the value of the resourceReleaseAtTermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource.ResourceReleaseAtTermination }
     *     
     */
    public void setResourceReleaseAtTermination(Resource.ResourceReleaseAtTermination value) {
        this.resourceReleaseAtTermination = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}NumericExpression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "add",
        "sub",
        "mul",
        "div",
        "sqrt",
        "abs",
        "integerVariable",
        "realVariable",
        "integerValue",
        "realValue",
        "lookupOnChange",
        "lookupNow",
        "nodeTimepointValue",
        "arraySize",
        "arrayMaxSize",
        "arrayElement"
    })
    public static class ResourceLowerBound {

        @XmlElement(name = "ADD")
        protected ADD add;
        @XmlElement(name = "SUB")
        protected SUB sub;
        @XmlElement(name = "MUL")
        protected MUL mul;
        @XmlElement(name = "DIV")
        protected DIV div;
        @XmlElement(name = "SQRT")
        protected SQRT sqrt;
        @XmlElement(name = "ABS")
        protected ABS abs;
        @XmlElement(name = "IntegerVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String integerVariable;
        @XmlElement(name = "RealVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String realVariable;
        @XmlElement(name = "IntegerValue")
        protected BigInteger integerValue;
        @XmlElement(name = "RealValue")
        protected Double realValue;
        @XmlElement(name = "LookupOnChange")
        protected LookupOnChange lookupOnChange;
        @XmlElement(name = "LookupNow")
        protected LookupNow lookupNow;
        @XmlElement(name = "NodeTimepointValue")
        protected NodeTimepointValue nodeTimepointValue;
        @XmlElement(name = "ArraySize")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String arraySize;
        @XmlElement(name = "ArrayMaxSize")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String arrayMaxSize;
        @XmlElement(name = "ArrayElement")
        protected ArrayElement arrayElement;

        /**
         * Gets the value of the add property.
         * 
         * @return
         *     possible object is
         *     {@link ADD }
         *     
         */
        public ADD getADD() {
            return add;
        }

        /**
         * Sets the value of the add property.
         * 
         * @param value
         *     allowed object is
         *     {@link ADD }
         *     
         */
        public void setADD(ADD value) {
            this.add = value;
        }

        /**
         * Gets the value of the sub property.
         * 
         * @return
         *     possible object is
         *     {@link SUB }
         *     
         */
        public SUB getSUB() {
            return sub;
        }

        /**
         * Sets the value of the sub property.
         * 
         * @param value
         *     allowed object is
         *     {@link SUB }
         *     
         */
        public void setSUB(SUB value) {
            this.sub = value;
        }

        /**
         * Gets the value of the mul property.
         * 
         * @return
         *     possible object is
         *     {@link MUL }
         *     
         */
        public MUL getMUL() {
            return mul;
        }

        /**
         * Sets the value of the mul property.
         * 
         * @param value
         *     allowed object is
         *     {@link MUL }
         *     
         */
        public void setMUL(MUL value) {
            this.mul = value;
        }

        /**
         * Gets the value of the div property.
         * 
         * @return
         *     possible object is
         *     {@link DIV }
         *     
         */
        public DIV getDIV() {
            return div;
        }

        /**
         * Sets the value of the div property.
         * 
         * @param value
         *     allowed object is
         *     {@link DIV }
         *     
         */
        public void setDIV(DIV value) {
            this.div = value;
        }

        /**
         * Gets the value of the sqrt property.
         * 
         * @return
         *     possible object is
         *     {@link SQRT }
         *     
         */
        public SQRT getSQRT() {
            return sqrt;
        }

        /**
         * Sets the value of the sqrt property.
         * 
         * @param value
         *     allowed object is
         *     {@link SQRT }
         *     
         */
        public void setSQRT(SQRT value) {
            this.sqrt = value;
        }

        /**
         * Gets the value of the abs property.
         * 
         * @return
         *     possible object is
         *     {@link ABS }
         *     
         */
        public ABS getABS() {
            return abs;
        }

        /**
         * Sets the value of the abs property.
         * 
         * @param value
         *     allowed object is
         *     {@link ABS }
         *     
         */
        public void setABS(ABS value) {
            this.abs = value;
        }

        /**
         * Gets the value of the integerVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntegerVariable() {
            return integerVariable;
        }

        /**
         * Sets the value of the integerVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntegerVariable(String value) {
            this.integerVariable = value;
        }

        /**
         * Gets the value of the realVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealVariable() {
            return realVariable;
        }

        /**
         * Sets the value of the realVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealVariable(String value) {
            this.realVariable = value;
        }

        /**
         * Gets the value of the integerValue property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIntegerValue() {
            return integerValue;
        }

        /**
         * Sets the value of the integerValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIntegerValue(BigInteger value) {
            this.integerValue = value;
        }

        /**
         * Gets the value of the realValue property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getRealValue() {
            return realValue;
        }

        /**
         * Sets the value of the realValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setRealValue(Double value) {
            this.realValue = value;
        }

        /**
         * Gets the value of the lookupOnChange property.
         * 
         * @return
         *     possible object is
         *     {@link LookupOnChange }
         *     
         */
        public LookupOnChange getLookupOnChange() {
            return lookupOnChange;
        }

        /**
         * Sets the value of the lookupOnChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupOnChange }
         *     
         */
        public void setLookupOnChange(LookupOnChange value) {
            this.lookupOnChange = value;
        }

        /**
         * Gets the value of the lookupNow property.
         * 
         * @return
         *     possible object is
         *     {@link LookupNow }
         *     
         */
        public LookupNow getLookupNow() {
            return lookupNow;
        }

        /**
         * Sets the value of the lookupNow property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupNow }
         *     
         */
        public void setLookupNow(LookupNow value) {
            this.lookupNow = value;
        }

        /**
         * Gets the value of the nodeTimepointValue property.
         * 
         * @return
         *     possible object is
         *     {@link NodeTimepointValue }
         *     
         */
        public NodeTimepointValue getNodeTimepointValue() {
            return nodeTimepointValue;
        }

        /**
         * Sets the value of the nodeTimepointValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link NodeTimepointValue }
         *     
         */
        public void setNodeTimepointValue(NodeTimepointValue value) {
            this.nodeTimepointValue = value;
        }

        /**
         * Gets the value of the arraySize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArraySize() {
            return arraySize;
        }

        /**
         * Sets the value of the arraySize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArraySize(String value) {
            this.arraySize = value;
        }

        /**
         * Gets the value of the arrayMaxSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrayMaxSize() {
            return arrayMaxSize;
        }

        /**
         * Sets the value of the arrayMaxSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrayMaxSize(String value) {
            this.arrayMaxSize = value;
        }

        /**
         * Gets the value of the arrayElement property.
         * 
         * @return
         *     possible object is
         *     {@link ArrayElement }
         *     
         */
        public ArrayElement getArrayElement() {
            return arrayElement;
        }

        /**
         * Sets the value of the arrayElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrayElement }
         *     
         */
        public void setArrayElement(ArrayElement value) {
            this.arrayElement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}StringExpression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stringVariable",
        "stringValue",
        "concat",
        "lookupOnChange",
        "lookupNow",
        "arrayElement"
    })
    public static class ResourceName {

        @XmlElement(name = "StringVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String stringVariable;
        @XmlElement(name = "StringValue")
        protected String stringValue;
        @XmlElement(name = "Concat")
        protected Concat concat;
        @XmlElement(name = "LookupOnChange")
        protected LookupOnChange lookupOnChange;
        @XmlElement(name = "LookupNow")
        protected LookupNow lookupNow;
        @XmlElement(name = "ArrayElement")
        protected ArrayElement arrayElement;

        /**
         * Gets the value of the stringVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStringVariable() {
            return stringVariable;
        }

        /**
         * Sets the value of the stringVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStringVariable(String value) {
            this.stringVariable = value;
        }

        /**
         * Gets the value of the stringValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStringValue() {
            return stringValue;
        }

        /**
         * Sets the value of the stringValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStringValue(String value) {
            this.stringValue = value;
        }

        /**
         * Gets the value of the concat property.
         * 
         * @return
         *     possible object is
         *     {@link Concat }
         *     
         */
        public Concat getConcat() {
            return concat;
        }

        /**
         * Sets the value of the concat property.
         * 
         * @param value
         *     allowed object is
         *     {@link Concat }
         *     
         */
        public void setConcat(Concat value) {
            this.concat = value;
        }

        /**
         * Gets the value of the lookupOnChange property.
         * 
         * @return
         *     possible object is
         *     {@link LookupOnChange }
         *     
         */
        public LookupOnChange getLookupOnChange() {
            return lookupOnChange;
        }

        /**
         * Sets the value of the lookupOnChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupOnChange }
         *     
         */
        public void setLookupOnChange(LookupOnChange value) {
            this.lookupOnChange = value;
        }

        /**
         * Gets the value of the lookupNow property.
         * 
         * @return
         *     possible object is
         *     {@link LookupNow }
         *     
         */
        public LookupNow getLookupNow() {
            return lookupNow;
        }

        /**
         * Sets the value of the lookupNow property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupNow }
         *     
         */
        public void setLookupNow(LookupNow value) {
            this.lookupNow = value;
        }

        /**
         * Gets the value of the arrayElement property.
         * 
         * @return
         *     possible object is
         *     {@link ArrayElement }
         *     
         */
        public ArrayElement getArrayElement() {
            return arrayElement;
        }

        /**
         * Sets the value of the arrayElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrayElement }
         *     
         */
        public void setArrayElement(ArrayElement value) {
            this.arrayElement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}NumericExpression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "add",
        "sub",
        "mul",
        "div",
        "sqrt",
        "abs",
        "integerVariable",
        "realVariable",
        "integerValue",
        "realValue",
        "lookupOnChange",
        "lookupNow",
        "nodeTimepointValue",
        "arraySize",
        "arrayMaxSize",
        "arrayElement"
    })
    public static class ResourcePriority {

        @XmlElement(name = "ADD")
        protected ADD add;
        @XmlElement(name = "SUB")
        protected SUB sub;
        @XmlElement(name = "MUL")
        protected MUL mul;
        @XmlElement(name = "DIV")
        protected DIV div;
        @XmlElement(name = "SQRT")
        protected SQRT sqrt;
        @XmlElement(name = "ABS")
        protected ABS abs;
        @XmlElement(name = "IntegerVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String integerVariable;
        @XmlElement(name = "RealVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String realVariable;
        @XmlElement(name = "IntegerValue")
        protected BigInteger integerValue;
        @XmlElement(name = "RealValue")
        protected Double realValue;
        @XmlElement(name = "LookupOnChange")
        protected LookupOnChange lookupOnChange;
        @XmlElement(name = "LookupNow")
        protected LookupNow lookupNow;
        @XmlElement(name = "NodeTimepointValue")
        protected NodeTimepointValue nodeTimepointValue;
        @XmlElement(name = "ArraySize")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String arraySize;
        @XmlElement(name = "ArrayMaxSize")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String arrayMaxSize;
        @XmlElement(name = "ArrayElement")
        protected ArrayElement arrayElement;

        /**
         * Gets the value of the add property.
         * 
         * @return
         *     possible object is
         *     {@link ADD }
         *     
         */
        public ADD getADD() {
            return add;
        }

        /**
         * Sets the value of the add property.
         * 
         * @param value
         *     allowed object is
         *     {@link ADD }
         *     
         */
        public void setADD(ADD value) {
            this.add = value;
        }

        /**
         * Gets the value of the sub property.
         * 
         * @return
         *     possible object is
         *     {@link SUB }
         *     
         */
        public SUB getSUB() {
            return sub;
        }

        /**
         * Sets the value of the sub property.
         * 
         * @param value
         *     allowed object is
         *     {@link SUB }
         *     
         */
        public void setSUB(SUB value) {
            this.sub = value;
        }

        /**
         * Gets the value of the mul property.
         * 
         * @return
         *     possible object is
         *     {@link MUL }
         *     
         */
        public MUL getMUL() {
            return mul;
        }

        /**
         * Sets the value of the mul property.
         * 
         * @param value
         *     allowed object is
         *     {@link MUL }
         *     
         */
        public void setMUL(MUL value) {
            this.mul = value;
        }

        /**
         * Gets the value of the div property.
         * 
         * @return
         *     possible object is
         *     {@link DIV }
         *     
         */
        public DIV getDIV() {
            return div;
        }

        /**
         * Sets the value of the div property.
         * 
         * @param value
         *     allowed object is
         *     {@link DIV }
         *     
         */
        public void setDIV(DIV value) {
            this.div = value;
        }

        /**
         * Gets the value of the sqrt property.
         * 
         * @return
         *     possible object is
         *     {@link SQRT }
         *     
         */
        public SQRT getSQRT() {
            return sqrt;
        }

        /**
         * Sets the value of the sqrt property.
         * 
         * @param value
         *     allowed object is
         *     {@link SQRT }
         *     
         */
        public void setSQRT(SQRT value) {
            this.sqrt = value;
        }

        /**
         * Gets the value of the abs property.
         * 
         * @return
         *     possible object is
         *     {@link ABS }
         *     
         */
        public ABS getABS() {
            return abs;
        }

        /**
         * Sets the value of the abs property.
         * 
         * @param value
         *     allowed object is
         *     {@link ABS }
         *     
         */
        public void setABS(ABS value) {
            this.abs = value;
        }

        /**
         * Gets the value of the integerVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntegerVariable() {
            return integerVariable;
        }

        /**
         * Sets the value of the integerVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntegerVariable(String value) {
            this.integerVariable = value;
        }

        /**
         * Gets the value of the realVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealVariable() {
            return realVariable;
        }

        /**
         * Sets the value of the realVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealVariable(String value) {
            this.realVariable = value;
        }

        /**
         * Gets the value of the integerValue property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIntegerValue() {
            return integerValue;
        }

        /**
         * Sets the value of the integerValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIntegerValue(BigInteger value) {
            this.integerValue = value;
        }

        /**
         * Gets the value of the realValue property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getRealValue() {
            return realValue;
        }

        /**
         * Sets the value of the realValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setRealValue(Double value) {
            this.realValue = value;
        }

        /**
         * Gets the value of the lookupOnChange property.
         * 
         * @return
         *     possible object is
         *     {@link LookupOnChange }
         *     
         */
        public LookupOnChange getLookupOnChange() {
            return lookupOnChange;
        }

        /**
         * Sets the value of the lookupOnChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupOnChange }
         *     
         */
        public void setLookupOnChange(LookupOnChange value) {
            this.lookupOnChange = value;
        }

        /**
         * Gets the value of the lookupNow property.
         * 
         * @return
         *     possible object is
         *     {@link LookupNow }
         *     
         */
        public LookupNow getLookupNow() {
            return lookupNow;
        }

        /**
         * Sets the value of the lookupNow property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupNow }
         *     
         */
        public void setLookupNow(LookupNow value) {
            this.lookupNow = value;
        }

        /**
         * Gets the value of the nodeTimepointValue property.
         * 
         * @return
         *     possible object is
         *     {@link NodeTimepointValue }
         *     
         */
        public NodeTimepointValue getNodeTimepointValue() {
            return nodeTimepointValue;
        }

        /**
         * Sets the value of the nodeTimepointValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link NodeTimepointValue }
         *     
         */
        public void setNodeTimepointValue(NodeTimepointValue value) {
            this.nodeTimepointValue = value;
        }

        /**
         * Gets the value of the arraySize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArraySize() {
            return arraySize;
        }

        /**
         * Sets the value of the arraySize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArraySize(String value) {
            this.arraySize = value;
        }

        /**
         * Gets the value of the arrayMaxSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrayMaxSize() {
            return arrayMaxSize;
        }

        /**
         * Sets the value of the arrayMaxSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrayMaxSize(String value) {
            this.arrayMaxSize = value;
        }

        /**
         * Gets the value of the arrayElement property.
         * 
         * @return
         *     possible object is
         *     {@link ArrayElement }
         *     
         */
        public ArrayElement getArrayElement() {
            return arrayElement;
        }

        /**
         * Sets the value of the arrayElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrayElement }
         *     
         */
        public void setArrayElement(ArrayElement value) {
            this.arrayElement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}BooleanExpression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "or",
        "xor",
        "and",
        "not",
        "isKnown",
        "gt",
        "ge",
        "lt",
        "le",
        "eqBoolean",
        "eqNumeric",
        "eqInternal",
        "eqString",
        "neBoolean",
        "neNumeric",
        "neInternal",
        "neString",
        "booleanVariable",
        "booleanValue",
        "lookupOnChange",
        "lookupNow",
        "arrayElement"
    })
    public static class ResourceReleaseAtTermination {

        @XmlElement(name = "OR")
        protected OR or;
        @XmlElement(name = "XOR")
        protected XOR xor;
        @XmlElement(name = "AND")
        protected AND and;
        @XmlElement(name = "NOT")
        protected NOT not;
        @XmlElement(name = "IsKnown")
        protected IsKnown isKnown;
        @XmlElement(name = "GT")
        protected GT gt;
        @XmlElement(name = "GE")
        protected GE ge;
        @XmlElement(name = "LT")
        protected LT lt;
        @XmlElement(name = "LE")
        protected LE le;
        @XmlElement(name = "EQBoolean")
        protected EQBoolean eqBoolean;
        @XmlElement(name = "EQNumeric")
        protected EQNumeric eqNumeric;
        @XmlElement(name = "EQInternal")
        protected EQInternal eqInternal;
        @XmlElement(name = "EQString")
        protected EQString eqString;
        @XmlElement(name = "NEBoolean")
        protected NEBoolean neBoolean;
        @XmlElement(name = "NENumeric")
        protected NENumeric neNumeric;
        @XmlElement(name = "NEInternal")
        protected NEInternal neInternal;
        @XmlElement(name = "NEString")
        protected NEString neString;
        @XmlElement(name = "BooleanVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String booleanVariable;
        @XmlElement(name = "BooleanValue")
        protected Boolean booleanValue;
        @XmlElement(name = "LookupOnChange")
        protected LookupOnChange lookupOnChange;
        @XmlElement(name = "LookupNow")
        protected LookupNow lookupNow;
        @XmlElement(name = "ArrayElement")
        protected ArrayElement arrayElement;

        /**
         * Gets the value of the or property.
         * 
         * @return
         *     possible object is
         *     {@link OR }
         *     
         */
        public OR getOR() {
            return or;
        }

        /**
         * Sets the value of the or property.
         * 
         * @param value
         *     allowed object is
         *     {@link OR }
         *     
         */
        public void setOR(OR value) {
            this.or = value;
        }

        /**
         * Gets the value of the xor property.
         * 
         * @return
         *     possible object is
         *     {@link XOR }
         *     
         */
        public XOR getXOR() {
            return xor;
        }

        /**
         * Sets the value of the xor property.
         * 
         * @param value
         *     allowed object is
         *     {@link XOR }
         *     
         */
        public void setXOR(XOR value) {
            this.xor = value;
        }

        /**
         * Gets the value of the and property.
         * 
         * @return
         *     possible object is
         *     {@link AND }
         *     
         */
        public AND getAND() {
            return and;
        }

        /**
         * Sets the value of the and property.
         * 
         * @param value
         *     allowed object is
         *     {@link AND }
         *     
         */
        public void setAND(AND value) {
            this.and = value;
        }

        /**
         * Gets the value of the not property.
         * 
         * @return
         *     possible object is
         *     {@link NOT }
         *     
         */
        public NOT getNOT() {
            return not;
        }

        /**
         * Sets the value of the not property.
         * 
         * @param value
         *     allowed object is
         *     {@link NOT }
         *     
         */
        public void setNOT(NOT value) {
            this.not = value;
        }

        /**
         * Gets the value of the isKnown property.
         * 
         * @return
         *     possible object is
         *     {@link IsKnown }
         *     
         */
        public IsKnown getIsKnown() {
            return isKnown;
        }

        /**
         * Sets the value of the isKnown property.
         * 
         * @param value
         *     allowed object is
         *     {@link IsKnown }
         *     
         */
        public void setIsKnown(IsKnown value) {
            this.isKnown = value;
        }

        /**
         * Gets the value of the gt property.
         * 
         * @return
         *     possible object is
         *     {@link GT }
         *     
         */
        public GT getGT() {
            return gt;
        }

        /**
         * Sets the value of the gt property.
         * 
         * @param value
         *     allowed object is
         *     {@link GT }
         *     
         */
        public void setGT(GT value) {
            this.gt = value;
        }

        /**
         * Gets the value of the ge property.
         * 
         * @return
         *     possible object is
         *     {@link GE }
         *     
         */
        public GE getGE() {
            return ge;
        }

        /**
         * Sets the value of the ge property.
         * 
         * @param value
         *     allowed object is
         *     {@link GE }
         *     
         */
        public void setGE(GE value) {
            this.ge = value;
        }

        /**
         * Gets the value of the lt property.
         * 
         * @return
         *     possible object is
         *     {@link LT }
         *     
         */
        public LT getLT() {
            return lt;
        }

        /**
         * Sets the value of the lt property.
         * 
         * @param value
         *     allowed object is
         *     {@link LT }
         *     
         */
        public void setLT(LT value) {
            this.lt = value;
        }

        /**
         * Gets the value of the le property.
         * 
         * @return
         *     possible object is
         *     {@link LE }
         *     
         */
        public LE getLE() {
            return le;
        }

        /**
         * Sets the value of the le property.
         * 
         * @param value
         *     allowed object is
         *     {@link LE }
         *     
         */
        public void setLE(LE value) {
            this.le = value;
        }

        /**
         * Gets the value of the eqBoolean property.
         * 
         * @return
         *     possible object is
         *     {@link EQBoolean }
         *     
         */
        public EQBoolean getEQBoolean() {
            return eqBoolean;
        }

        /**
         * Sets the value of the eqBoolean property.
         * 
         * @param value
         *     allowed object is
         *     {@link EQBoolean }
         *     
         */
        public void setEQBoolean(EQBoolean value) {
            this.eqBoolean = value;
        }

        /**
         * Gets the value of the eqNumeric property.
         * 
         * @return
         *     possible object is
         *     {@link EQNumeric }
         *     
         */
        public EQNumeric getEQNumeric() {
            return eqNumeric;
        }

        /**
         * Sets the value of the eqNumeric property.
         * 
         * @param value
         *     allowed object is
         *     {@link EQNumeric }
         *     
         */
        public void setEQNumeric(EQNumeric value) {
            this.eqNumeric = value;
        }

        /**
         * Gets the value of the eqInternal property.
         * 
         * @return
         *     possible object is
         *     {@link EQInternal }
         *     
         */
        public EQInternal getEQInternal() {
            return eqInternal;
        }

        /**
         * Sets the value of the eqInternal property.
         * 
         * @param value
         *     allowed object is
         *     {@link EQInternal }
         *     
         */
        public void setEQInternal(EQInternal value) {
            this.eqInternal = value;
        }

        /**
         * Gets the value of the eqString property.
         * 
         * @return
         *     possible object is
         *     {@link EQString }
         *     
         */
        public EQString getEQString() {
            return eqString;
        }

        /**
         * Sets the value of the eqString property.
         * 
         * @param value
         *     allowed object is
         *     {@link EQString }
         *     
         */
        public void setEQString(EQString value) {
            this.eqString = value;
        }

        /**
         * Gets the value of the neBoolean property.
         * 
         * @return
         *     possible object is
         *     {@link NEBoolean }
         *     
         */
        public NEBoolean getNEBoolean() {
            return neBoolean;
        }

        /**
         * Sets the value of the neBoolean property.
         * 
         * @param value
         *     allowed object is
         *     {@link NEBoolean }
         *     
         */
        public void setNEBoolean(NEBoolean value) {
            this.neBoolean = value;
        }

        /**
         * Gets the value of the neNumeric property.
         * 
         * @return
         *     possible object is
         *     {@link NENumeric }
         *     
         */
        public NENumeric getNENumeric() {
            return neNumeric;
        }

        /**
         * Sets the value of the neNumeric property.
         * 
         * @param value
         *     allowed object is
         *     {@link NENumeric }
         *     
         */
        public void setNENumeric(NENumeric value) {
            this.neNumeric = value;
        }

        /**
         * Gets the value of the neInternal property.
         * 
         * @return
         *     possible object is
         *     {@link NEInternal }
         *     
         */
        public NEInternal getNEInternal() {
            return neInternal;
        }

        /**
         * Sets the value of the neInternal property.
         * 
         * @param value
         *     allowed object is
         *     {@link NEInternal }
         *     
         */
        public void setNEInternal(NEInternal value) {
            this.neInternal = value;
        }

        /**
         * Gets the value of the neString property.
         * 
         * @return
         *     possible object is
         *     {@link NEString }
         *     
         */
        public NEString getNEString() {
            return neString;
        }

        /**
         * Sets the value of the neString property.
         * 
         * @param value
         *     allowed object is
         *     {@link NEString }
         *     
         */
        public void setNEString(NEString value) {
            this.neString = value;
        }

        /**
         * Gets the value of the booleanVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBooleanVariable() {
            return booleanVariable;
        }

        /**
         * Sets the value of the booleanVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBooleanVariable(String value) {
            this.booleanVariable = value;
        }

        /**
         * Gets the value of the booleanValue property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBooleanValue() {
            return booleanValue;
        }

        /**
         * Sets the value of the booleanValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBooleanValue(Boolean value) {
            this.booleanValue = value;
        }

        /**
         * Gets the value of the lookupOnChange property.
         * 
         * @return
         *     possible object is
         *     {@link LookupOnChange }
         *     
         */
        public LookupOnChange getLookupOnChange() {
            return lookupOnChange;
        }

        /**
         * Sets the value of the lookupOnChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupOnChange }
         *     
         */
        public void setLookupOnChange(LookupOnChange value) {
            this.lookupOnChange = value;
        }

        /**
         * Gets the value of the lookupNow property.
         * 
         * @return
         *     possible object is
         *     {@link LookupNow }
         *     
         */
        public LookupNow getLookupNow() {
            return lookupNow;
        }

        /**
         * Sets the value of the lookupNow property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupNow }
         *     
         */
        public void setLookupNow(LookupNow value) {
            this.lookupNow = value;
        }

        /**
         * Gets the value of the arrayElement property.
         * 
         * @return
         *     possible object is
         *     {@link ArrayElement }
         *     
         */
        public ArrayElement getArrayElement() {
            return arrayElement;
        }

        /**
         * Sets the value of the arrayElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrayElement }
         *     
         */
        public void setArrayElement(ArrayElement value) {
            this.arrayElement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{}NumericExpression"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "add",
        "sub",
        "mul",
        "div",
        "sqrt",
        "abs",
        "integerVariable",
        "realVariable",
        "integerValue",
        "realValue",
        "lookupOnChange",
        "lookupNow",
        "nodeTimepointValue",
        "arraySize",
        "arrayMaxSize",
        "arrayElement"
    })
    public static class ResourceUpperBound {

        @XmlElement(name = "ADD")
        protected ADD add;
        @XmlElement(name = "SUB")
        protected SUB sub;
        @XmlElement(name = "MUL")
        protected MUL mul;
        @XmlElement(name = "DIV")
        protected DIV div;
        @XmlElement(name = "SQRT")
        protected SQRT sqrt;
        @XmlElement(name = "ABS")
        protected ABS abs;
        @XmlElement(name = "IntegerVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String integerVariable;
        @XmlElement(name = "RealVariable")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String realVariable;
        @XmlElement(name = "IntegerValue")
        protected BigInteger integerValue;
        @XmlElement(name = "RealValue")
        protected Double realValue;
        @XmlElement(name = "LookupOnChange")
        protected LookupOnChange lookupOnChange;
        @XmlElement(name = "LookupNow")
        protected LookupNow lookupNow;
        @XmlElement(name = "NodeTimepointValue")
        protected NodeTimepointValue nodeTimepointValue;
        @XmlElement(name = "ArraySize")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String arraySize;
        @XmlElement(name = "ArrayMaxSize")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "NCName")
        protected String arrayMaxSize;
        @XmlElement(name = "ArrayElement")
        protected ArrayElement arrayElement;

        /**
         * Gets the value of the add property.
         * 
         * @return
         *     possible object is
         *     {@link ADD }
         *     
         */
        public ADD getADD() {
            return add;
        }

        /**
         * Sets the value of the add property.
         * 
         * @param value
         *     allowed object is
         *     {@link ADD }
         *     
         */
        public void setADD(ADD value) {
            this.add = value;
        }

        /**
         * Gets the value of the sub property.
         * 
         * @return
         *     possible object is
         *     {@link SUB }
         *     
         */
        public SUB getSUB() {
            return sub;
        }

        /**
         * Sets the value of the sub property.
         * 
         * @param value
         *     allowed object is
         *     {@link SUB }
         *     
         */
        public void setSUB(SUB value) {
            this.sub = value;
        }

        /**
         * Gets the value of the mul property.
         * 
         * @return
         *     possible object is
         *     {@link MUL }
         *     
         */
        public MUL getMUL() {
            return mul;
        }

        /**
         * Sets the value of the mul property.
         * 
         * @param value
         *     allowed object is
         *     {@link MUL }
         *     
         */
        public void setMUL(MUL value) {
            this.mul = value;
        }

        /**
         * Gets the value of the div property.
         * 
         * @return
         *     possible object is
         *     {@link DIV }
         *     
         */
        public DIV getDIV() {
            return div;
        }

        /**
         * Sets the value of the div property.
         * 
         * @param value
         *     allowed object is
         *     {@link DIV }
         *     
         */
        public void setDIV(DIV value) {
            this.div = value;
        }

        /**
         * Gets the value of the sqrt property.
         * 
         * @return
         *     possible object is
         *     {@link SQRT }
         *     
         */
        public SQRT getSQRT() {
            return sqrt;
        }

        /**
         * Sets the value of the sqrt property.
         * 
         * @param value
         *     allowed object is
         *     {@link SQRT }
         *     
         */
        public void setSQRT(SQRT value) {
            this.sqrt = value;
        }

        /**
         * Gets the value of the abs property.
         * 
         * @return
         *     possible object is
         *     {@link ABS }
         *     
         */
        public ABS getABS() {
            return abs;
        }

        /**
         * Sets the value of the abs property.
         * 
         * @param value
         *     allowed object is
         *     {@link ABS }
         *     
         */
        public void setABS(ABS value) {
            this.abs = value;
        }

        /**
         * Gets the value of the integerVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntegerVariable() {
            return integerVariable;
        }

        /**
         * Sets the value of the integerVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntegerVariable(String value) {
            this.integerVariable = value;
        }

        /**
         * Gets the value of the realVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRealVariable() {
            return realVariable;
        }

        /**
         * Sets the value of the realVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRealVariable(String value) {
            this.realVariable = value;
        }

        /**
         * Gets the value of the integerValue property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIntegerValue() {
            return integerValue;
        }

        /**
         * Sets the value of the integerValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIntegerValue(BigInteger value) {
            this.integerValue = value;
        }

        /**
         * Gets the value of the realValue property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getRealValue() {
            return realValue;
        }

        /**
         * Sets the value of the realValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setRealValue(Double value) {
            this.realValue = value;
        }

        /**
         * Gets the value of the lookupOnChange property.
         * 
         * @return
         *     possible object is
         *     {@link LookupOnChange }
         *     
         */
        public LookupOnChange getLookupOnChange() {
            return lookupOnChange;
        }

        /**
         * Sets the value of the lookupOnChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupOnChange }
         *     
         */
        public void setLookupOnChange(LookupOnChange value) {
            this.lookupOnChange = value;
        }

        /**
         * Gets the value of the lookupNow property.
         * 
         * @return
         *     possible object is
         *     {@link LookupNow }
         *     
         */
        public LookupNow getLookupNow() {
            return lookupNow;
        }

        /**
         * Sets the value of the lookupNow property.
         * 
         * @param value
         *     allowed object is
         *     {@link LookupNow }
         *     
         */
        public void setLookupNow(LookupNow value) {
            this.lookupNow = value;
        }

        /**
         * Gets the value of the nodeTimepointValue property.
         * 
         * @return
         *     possible object is
         *     {@link NodeTimepointValue }
         *     
         */
        public NodeTimepointValue getNodeTimepointValue() {
            return nodeTimepointValue;
        }

        /**
         * Sets the value of the nodeTimepointValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link NodeTimepointValue }
         *     
         */
        public void setNodeTimepointValue(NodeTimepointValue value) {
            this.nodeTimepointValue = value;
        }

        /**
         * Gets the value of the arraySize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArraySize() {
            return arraySize;
        }

        /**
         * Sets the value of the arraySize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArraySize(String value) {
            this.arraySize = value;
        }

        /**
         * Gets the value of the arrayMaxSize property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrayMaxSize() {
            return arrayMaxSize;
        }

        /**
         * Sets the value of the arrayMaxSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrayMaxSize(String value) {
            this.arrayMaxSize = value;
        }

        /**
         * Gets the value of the arrayElement property.
         * 
         * @return
         *     possible object is
         *     {@link ArrayElement }
         *     
         */
        public ArrayElement getArrayElement() {
            return arrayElement;
        }

        /**
         * Sets the value of the arrayElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link ArrayElement }
         *     
         */
        public void setArrayElement(ArrayElement value) {
            this.arrayElement = value;
        }
        

    }

}
