in micro.maude
in macro.maude
in syncred.maude
in values.maude

mod TEST--REDUCTIONS is

  pr TEST--REDUCTIONS--MICRO .
  pr TEST--REDUCTIONS--MACRO .
  pr TEST--REDUCTIONS--SYNCRED .
  pr TEST--REDUCTIONS--VALUES .

  op reductions--tests : -> TestResults .

  eq reductions--tests =
    micro--reductions--tests
    + values--reductions--tests
    + test--reductions--macro
    + test--reductions--syncred
    .

endm